name: frame-diagnostic
version: '0.1'
summary: example diagnostic
description: Demo of Ubuntu Frame's diagnostic
base: core20
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

plugs:
  ubuntu-frame-diagnostic:
    interface: content
    content: writable-data
    target: $SNAP_COMMON/diagnostic
    default-provider: ubuntu-frame

environment:
  DIAGNOSTIC_FILE: $SNAP_COMMON/diagnostic/diagnostic.txt

apps:
  frame-diagnostic:
    command: write-diagnostic

parts:
  write-diagnostic:
    plugin: dump
    source: script